# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TFSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TFSwiftDemo
  
  pod 'TFThisshopKit', :podspec => 'https://raw.githubusercontent.com/thaifintech-hub/TFThisshopKit/main/iOS/TFThisshopKit.podspec'

  target 'TFSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TFSwiftDemoUITests' do
    # Pods for testing
  end

end
